# fly.toml app configuration file generated for pdfcraftify on 2023-10-25T22:42:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdfcraftify"
primary_region = "hkg"

[build]

[build.args]
    # Kinde for secure, fast authentication 
    KINDE_CLIENT_ID=8b8f973fa3364dc1a952f85c2b4e9374
    KINDE_CLIENT_SECRET=cg6bKt7iLZAzv7H5FvoWMOhV4sXPqhdTza9nXt4N1vEl5ymk1ktV2
    KINDE_ISSUER_URL=https://pdfcraftify.kinde.com
    KINDE_SITE_URL=http://localhost:3000
    KINDE_POST_LOGOUT_REDIRECT_URL=http://localhost:3000
    KINDE_POST_LOGIN_REDIRECT_URL=http://localhost:3000/dashboard

    # Database for storing everything except PDF files - (Provider up to you, I like PlanetScale)
    DATABASE_URL="postgres://vahsir87:XtR6GB8lKdcC@ep-wild-voice-99723620.ap-southeast-1.aws.neon.tech/PdfCraftifyDB"

    # Uploadthing for storing PDF files - https://uploadthing.com/dashboard
    UPLOADTHING_SECRET=sk_live_42f453a1643319c85f46b6dfbfd71a0858951533d273edbc2a85b74a590e4a3d
    UPLOADTHING_APP_ID=mj5ce2zg5r

    # OpenAI for answering PDF questions - https://platform.openai.com/
    OPENAI_API_KEY=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

    # Stripe for payment processing - https://stripe.com/
    STRIPE_SECRET_KEY=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
    STRIPE_WEBHOOK_SECRET=whsec_dd77j8m0N5LDqVbGbEqvVW3w3P54A4PX

    # Pinecone for long-term vector storage - https://www.pinecone.io/
    PINECONE_API_KEY=1afee584-1eac-47b3-9467-0fae4c688463


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
